# Generated by Django 4.1.4 on 2022-12-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_activate', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='student-media')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
