# Generated by Django 4.1.4 on 2023-01-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0003_student_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='create',
            new_name='created',
        ),
    ]
