# Generated by Django 4.1.4 on 2023-01-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='start_date',
        ),
    ]
