# Generated by Django 4.1.4 on 2023-01-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_alter_person_gender_alter_person_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='start_date',
        ),
    ]
