# Generated by Django 4.1.4 on 2023-01-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_alter_person_departmen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='departmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department', to='person.department'),
        ),
    ]
