# Generated by Django 4.1.5 on 2023-01-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_person_current_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='current_user',
            new_name='user',
        ),
    ]
