# Generated by Django 4.1.5 on 2023-01-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dispaly_name',
            new_name='display_name',
        ),
    ]
